import Link from 'next/link';
import './globals.css';
import { Control } from './Control';
import { PostsProvider } from './postsProvider';

export const metadata = {
  title: 'WEB tutorial',
  description: 'Generated by egoing',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}posts/list`,
    { cache: 'no-store' }
  );
  const posts = await resp.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <PostsProvider initialPosts={posts.data}>
          {children}
          <Control />
          <ol>
            {posts.data.map((post: { _id: string; title: string }) => (
              <li key={post._id}>
                <Link href={`/read/${post._id}`}>{post.title}</Link>
              </li>
            ))}
          </ol>
        </PostsProvider>
      </body>
    </html>
  );
}